name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run Go Tests
        run:  go test ./... 
         
      - name: Run Go test with coverage
        run: go test -cover ./...
    
  style:  
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version: "1.25.1"

      - name: Run Test -z
        run: test -z "$(go fmt ./...)" 

      - name: Run Go Formatting
        run: go fmt ./...
   