# Die Datei, die bei jedem Push auf den main-Branch automatisch:
# 1. Mit GCP authentifiziert
# 2. Das Docker-Image baut
# 3. Es in die Artifact Registry hochlaedt

name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tensile-core-474113-t6

      - name: Show gcloud config
        run: gcloud config list

      - name: Who am I
        run: gcloud auth list

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/tensile-core-474113-t6/notely-ar-repo/notely:latest .