#security.yml
name: Security Pipeline

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

jobs:
  security-check:
    name: Security & Compliance Scan
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secret scan (TruffleHog)
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .

      - name: Dependency vulnerability scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: 0
          scanners: 'vuln,secret,config'

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: trivy-results.txt
          